# Generated by Django 4.1.4 on 2022-12-24 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'ClassField',
            },
        ),
        migrations.CreateModel(
            name='Fertilizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fertilizer_name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'Fertilizer',
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_name', models.CharField(max_length=50)),
                ('seed_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'Plant',
            },
        ),
        migrations.CreateModel(
            name='PredictedCrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_crop_name', models.CharField(max_length=50)),
                ('crop_mass', models.DecimalField(decimal_places=2, max_digits=10)),
                ('class_field', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, to='fields.classfield')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fields.plant')),
            ],
            options={
                'db_table': 'PredictedCrop',
            },
        ),
        migrations.CreateModel(
            name='PlantPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('date', models.DateField()),
                ('is_predicted', models.BooleanField()),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fields.plant')),
            ],
            options={
                'db_table': 'PlantPrice',
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=50)),
                ('area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('class_field', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, to='fields.classfield')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Field',
            },
        ),
        migrations.CreateModel(
            name='FertilizationPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fertilizer_mass', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fertilizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fields.fertilizer')),
                ('predicted_crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fields.predictedcrop')),
            ],
            options={
                'db_table': 'FertilizationPlan',
            },
        ),
    ]
