# Generated by Django 4.1.3 on 2022-11-29 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'ClassField',
            },
        ),
        migrations.CreateModel(
            name='FertilizationPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fertilizer_mass', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'FertilizationPlan',
            },
        ),
        migrations.CreateModel(
            name='Fertilizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fertilizer_name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'Fertilizer',
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_name', models.CharField(max_length=50)),
                ('seed_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'Plant',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='PredictedCrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_mass', models.DecimalField(decimal_places=2, max_digits=10)),
                ('class_field', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, to='fields.classfield')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fields.plant')),
            ],
            options={
                'db_table': 'PredictedCrop',
            },
        ),
        migrations.CreateModel(
            name='PlantPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('is_predicted', models.BooleanField()),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fields.plant')),
            ],
            options={
                'db_table': 'PlantPrice',
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fertilization_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fields.fertilizationplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fields.user')),
            ],
            options={
                'db_table': 'Field',
            },
        ),
        migrations.AddField(
            model_name='fertilizationplan',
            name='fertilizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fields.fertilizer'),
        ),
        migrations.AddField(
            model_name='fertilizationplan',
            name='predicted_crop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fields.predictedcrop'),
        ),
    ]
